[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi-users-db-sqlalchemy>=7.0.0",
    "fastapi>=0.115.12",
    "sqlalchemy>=2.0.41",
    "uvicorn>=0.34.2",
]
