"""add topics and languages to user

Revision ID: 54027bef38e7
Revises: 
Create Date: 2025-05-25 01:07:40.137660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54027bef38e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('topics', sa.String(), nullable=True))
    op.add_column('users', sa.Column('languages', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'languages')
    op.drop_column('users', 'topics')
    # ### end Alembic commands ###
